"""Init migration Rooms, Booking, Users

Revision ID: 825ca29ddcd6
Revises: a8836df0c696
Create Date: 2025-11-06 08:50:49.812854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '825ca29ddcd6'
down_revision: Union[str, Sequence[str], None] = 'a8836df0c696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('service', sa.JSON(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('room_id', sa.Integer(), nullable=True),
            sa.Column('user_id', sa.Integer(), nullable=True),
            sa.Column('date_from', sa.DateTime(), nullable=False),
            sa.Column('date_to', sa.DateTime(), nullable=False),
            sa.Column('price', sa.Integer(), nullable=False),

            sa.Column(
                'total_days',
                sa.Integer(),
                sa.Computed("(EXTRACT(EPOCH FROM (date_to - date_from)) / 86400)::int"),
                nullable=False
            ),

                    # целые дни * цена -> integer
            sa.Column(
                'total_cost',
                sa.Integer(),
                sa.Computed("((EXTRACT(EPOCH FROM (date_to - date_from)) / 86400)::int * price)"),
                nullable=False
            ),
            sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.CheckConstraint('date_to >= date_from', name='ck_bookings_dates_order'),
    )
    op.alter_column('hotels', 'service',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hotels', 'service',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_table('bookings')
    op.drop_table('rooms')
    op.drop_table('users')
    # ### end Alembic commands ###
